version: '3.8'

services:
  app:
    image: express-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/stack-docker
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:latest 
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    external: true
    name: app-network

volumes:
  mongo_data: