name: Crear y subir imagen de docker 

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: construir imagen
        run: docker build -t pablop19/ejemplo3:latest .

      - name: iniciar sesion en docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: subir imagen
        run: docker push pablop19/ejemplo3:latest
